mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: info

server:
  port: 8080
  servlet:
    session:
      timeout: 64800
      cookie:
        path: /
        max-age: 64800
    context-path: ''

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    appId: socket-app
    name: socket-app
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization: {WRITE_DATES_AS_TIMESTAMPS: true}
    deserialization:
      fail-on-unknown-properties: false
      fail-on-invalid-subtype: false
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev218-mgr-internal.softium.cn:3310/mdm_enterprise_play?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: mdm-master-play
    password: Smp#2020
    druid:
      min-idle: 10
      initial-size: 10
      max-active: 50
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 600000
      valid-connection-checker-class-name: com.alibaba.druid.pool.vendor.MySqlValidConnectionChecker
      db-type: mysql
      filter:
        stat:
          enabled: true
